[package]
name = "hashtag"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "hashtag_macros",
]

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
hashtag_macros = { path = "hashtag_macros" }